import { HttpStatus, Injectable } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';
import { CARD_SCHEMA_BY_SECTION, type SectionReply } from '../../ai/index.js';
import { generateId } from '../../common/ids.js';
import { AppError } from '../../common/errors/app-error.js';
import { RawResponseException } from '../../common/errors/raw-response.exception.js';
import { DEFAULT_BUILD_SECTIONS, SECTION_LABELS, type SectionId, type SessionStatus } from '../../common/types/contract.js';
import type { LlmMessage } from '../../integrations/llm/llm.interface.js';
import { CvService } from '../cv/index.js';
import { UploadService } from '../upload/index.js';
import { ConversationRepository } from './conversation.repository.js';
import type { ConfirmSectionDto } from './dto/confirm-section.dto.js';
import type { ConfirmSectionResponseDto } from './dto/confirm-section-response.dto.js';
import { toMessageResponseDto, type ConversationResponseDto } from './dto/conversation-response.dto.js';
import type { CreateConversationDto } from './dto/create-conversation.dto.js';
import type { SendMessageDto } from './dto/send-message.dto.js';
import type { ConversationSession, SessionSection } from './entities/conversation-session.entity.js';
import type { Message } from './entities/message.entity.js';

/**
 * Fixed, written-in-code text for entering each section — not generated by the model. It's always
 * the same for a given transition, so there's no reason to pay for an LLM call or make the user wait
 * for it. Used both to open a brand-new build-mode session (`basic`) and, on confirm, to greet
 * whichever section comes next.
 */
const SECTION_OPENING_MESSAGES: Record<SectionId, string> = {
  basic: 'أهلًا! هساعدك تعمل CV محترم في دقايق، من غير ما تكتب ولا حرف. نبدأ بإيه اسمك؟',
  experience: 'تمام. نتكلم بقى عن خبرتك — اشتغلت قبل كده في أي مكان؟',
  projects: 'تمام، بما إنك لسه ما اشتغلتش، يبقى نتكلم عن أي مشاريع عملتها — في الكلية أو لوحدك؟',
  education: 'جميل. نتكلم عن تعليمك — اتخرجت في إيه ومن فين؟',
  certificates: 'حلو. عندك شهادات أو كورسات خدتها؟',
  skills: 'تمام. إيه أهم المهارات اللي تشتغل بيها؟',
  languages: 'آخر حاجة، اللغات اللي بتتكلمها وإيه مستواك فيها؟',
};

/** Sent as the `nextMessage` on the confirm that closes the CV (no `nextSection` left). */
const CV_COMPLETE_MESSAGE = 'مبروك! خلصنا الـ CV بتاعك 🎉 تقدر تراجعه دلوقتي وتعدل أي حاجة قبل ما تحمّله.';

export interface ActiveSessionSummary {
  activeSessionId: string | null;
  completedSections: SectionId[];
  nextSection: SectionId | null;
}

@Injectable()
export class ConversationService {
  constructor(
    private readonly conversationRepository: ConversationRepository,
    private readonly cvService: CvService,
    private readonly uploadService: UploadService,
    @InjectDataSource() private readonly dataSource: DataSource,
  ) {}

  async create(deviceId: string, dto: CreateConversationDto): Promise<ConversationResponseDto> {
    // Validate an upload before touching an existing session. A typo/stale upload id must never
    // destroy the conversation the user can still resume.
    const uploadAnalysis =
      dto.mode === 'upload'
        ? dto.uploadId
          ? await this.uploadService.getCompletedAnalysis(dto.uploadId, deviceId)
          : null
        : null;
    if (dto.mode === 'upload' && !dto.uploadId) {
      throw new AppError('INVALID_REQUEST', 'لازم تبعت رقم ملف الـ CV اللي اتحلل', { retryable: false });
    }

    const existing = await this.conversationRepository.findActiveByDeviceId(deviceId);
    if (existing) {
      if (!dto.restart) {
        throw new RawResponseException(HttpStatus.CONFLICT, { activeSessionId: existing.id });
      }
      if (dto.mode === 'upload') {
        // Upload analysis has already replaced the device's CV with its high-confidence sections.
        // Restart only the old chat here; deleting that CV would throw away the freshly parsed data.
        await this.conversationRepository.deleteById(existing.id);
      } else {
        await this.deleteSessionAndItsCv(existing);
      }
    }

    let sectionIds = DEFAULT_BUILD_SECTIONS;
    let cvId: string | null = null;
    if (dto.mode === 'upload') {
      // `uploadAnalysis` can only be null for a missing upload id, rejected above.
      const analysis = uploadAnalysis!;
      sectionIds = DEFAULT_BUILD_SECTIONS.filter((id) => analysis.sectionConfidence[id] === 'low');
      // Projects isn't in the default build list, but can be the missing work-proof section for a
      // project-led CV. Include it exactly where experience would normally appear.
      if (analysis.sectionConfidence.projects === 'low' && !sectionIds.includes('projects')) {
        const experienceIndex = sectionIds.indexOf('experience');
        sectionIds.splice(experienceIndex === -1 ? 1 : experienceIndex, 0, 'projects');
      }
      cvId = (await this.cvService.getForDevice(deviceId)).cvId;
    }

    const sections: SessionSection[] = sectionIds.map((id) => ({
      id,
      label: SECTION_LABELS[id],
      status: 'pending',
    }));

    const currentSection = sections[0]?.id ?? null;
    const sessionStatus = currentSection ? 'in_progress' : 'completed';
    let openingText = currentSection ? SECTION_OPENING_MESSAGES[currentSection] : CV_COMPLETE_MESSAGE;
    if (dto.mode === 'upload' && currentSection === 'basic' && uploadAnalysis) {
      const basic = uploadAnalysis.cv.basic;
      if (!basic.title) {
        openingText = 'قرأنا اسمك من الملف. إيه المسمى الوظيفي بتاعك، أو الوظيفة اللي بتدور عليها؟';
      } else if (!basic.phone && !basic.email) {
        openingText = 'البيانات الأساسية واضحة، ناقص بس وسيلة تواصل. ممكن رقم موبايلك أو إيميلك؟';
      }
    }

    const session = await this.conversationRepository.create({
      id: generateId('cnv'),
      deviceId,
      mode: dto.mode,
      status: sessionStatus,
      currentSection,
      sections,
      uploadId: dto.mode === 'upload' ? (dto.uploadId ?? null) : null,
      cvId,
    });

    // Persisted as a normal assistant message so it comes back with GET /conversations/:id and is
    // part of the history the model itself sees on the first real reply — not a client-side-only
    // greeting.
    const openingMessage = await this.conversationRepository.createMessage({
      id: generateId('msg'),
      sessionId: session.id,
      role: 'ai',
      section: session.currentSection,
      type: 'text',
      text: openingText,
      card: null,
      quickReplies: null,
      source: null,
      audioDurationSec: null,
    });

    return this.toResponseDto(session, [openingMessage]);
  }

  async findByIdForDevice(sessionId: string, deviceId: string): Promise<ConversationResponseDto> {
    const session = await this.getOwnedSession(sessionId, deviceId);
    const messages = await this.conversationRepository.findMessagesBySessionId(session.id);
    return this.toResponseDto(session, messages);
  }

  async deleteByIdForDevice(sessionId: string, deviceId: string): Promise<void> {
    const session = await this.getOwnedSession(sessionId, deviceId);
    await this.deleteSessionAndItsCv(session);
  }

  async getActiveSessionSummary(deviceId: string): Promise<ActiveSessionSummary> {
    const session = await this.conversationRepository.findActiveByDeviceId(deviceId);
    if (!session) {
      return { activeSessionId: null, completedSections: [], nextSection: null };
    }
    return {
      activeSessionId: session.id,
      completedSections: session.sections.filter((section) => section.status === 'confirmed').map((section) => section.id),
      nextSection: session.currentSection,
    };
  }

  /** Only sessions still `in_progress` can be messaged. */
  async getActiveOwnedSession(sessionId: string, deviceId: string): Promise<ConversationSession> {
    const session = await this.getOwnedSession(sessionId, deviceId);
    if (session.status !== 'in_progress') {
      throw new AppError('INVALID_REQUEST', 'الجلسة دي خلصت خلاص', { retryable: false });
    }
    return session;
  }

  /**
   * Prior text messages for the CURRENT section only, oldest first, mapped
   * for the LLM prompt — section_card messages have no natural-language text
   * and are skipped, and other sections' chatter is excluded so the model
   * (and the fake provider, which counts entries this way) only ever sees
   * this section's own back-and-forth.
   */
  async getMessageHistoryForPrompt(sessionId: string, section: SectionId): Promise<LlmMessage[]> {
    const messages = await this.conversationRepository.findMessagesBySessionId(sessionId);
    return messages
      .filter((message) => message.type === 'text' && message.text && message.section === section)
      .map((message) => ({ role: message.role === 'ai' ? ('assistant' as const) : ('user' as const), content: message.text as string }));
  }

  /**
   * The largest `section_card` this section has produced so far this conversation (there can be
   * several unconfirmed attempts if the model closed the section more than once before the user
   * confirmed) — array-shaped cards compare by entry count, object-shaped cards just use the most
   * recent. Passed into SectionReplyService so a new extraction that comes back with fewer entries
   * than an earlier attempt can be recognized as data loss rather than the user's own edit.
   */
  async getBestPriorSectionCard(sessionId: string, section: SectionId): Promise<Record<string, unknown> | unknown[] | null> {
    const session = await this.conversationRepository.findById(sessionId);
    const messages = await this.conversationRepository.findMessagesBySessionId(sessionId);
    const cards = messages.filter((message) => message.type === 'section_card' && message.section === section && message.card !== null).map((message) => message.card as Record<string, unknown> | unknown[]);
    if (cards.length === 0) {
      if (session?.mode === 'upload' && session.uploadId) {
        const analysis = await this.cvService.getAnalysisForUpload(session.uploadId, session.deviceId);
        return (analysis?.cv[section] as Record<string, unknown> | unknown[] | undefined) ?? null;
      }
      return null;
    }
    const arrays = cards.filter((card): card is unknown[] => Array.isArray(card));
    if (arrays.length > 0) {
      return arrays.reduce((best, card) => (card.length > best.length ? card : best));
    }
    return cards[cards.length - 1] ?? null;
  }

  /** Every section card this session has produced (confirmed or not), oldest first — ownership-checked, any session status. */
  async getSectionCardsForDevice(sessionId: string, deviceId: string): Promise<Array<Record<string, unknown> | unknown[]>> {
    const session = await this.getOwnedSession(sessionId, deviceId);
    const messages = await this.conversationRepository.findMessagesBySessionId(session.id);
    return messages
      .filter((message) => message.type === 'section_card' && message.card !== null)
      .map((message) => message.card as Record<string, unknown> | unknown[]);
  }

  appendUserMessage(session: ConversationSession, dto: SendMessageDto): Promise<Message> {
    return this.conversationRepository.createMessage({
      id: generateId('msg'),
      sessionId: session.id,
      role: 'user',
      section: session.currentSection,
      type: 'text',
      text: dto.text,
      card: null,
      quickReplies: null,
      source: dto.source,
      audioDurationSec: dto.audioDurationSec ?? null,
    });
  }

  appendAiTextMessage(session: ConversationSession, reply: SectionReply): Promise<Message> {
    return this.conversationRepository.createMessage({
      id: generateId('msg'),
      sessionId: session.id,
      role: 'ai',
      section: reply.section,
      type: 'text',
      text: reply.message,
      card: null,
      quickReplies: null,
      source: null,
      audioDurationSec: null,
    });
  }

  appendSectionCardMessage(session: ConversationSession, reply: SectionReply): Promise<Message> {
    return this.conversationRepository.createMessage({
      id: generateId('msg'),
      sessionId: session.id,
      role: 'ai',
      section: reply.section,
      type: 'section_card',
      text: null,
      // reply.card's exact shape depends on reply.section (see CARD_SCHEMA_BY_SECTION); by now it's already zod-validated.
      card: reply.card as Record<string, unknown> | unknown[] | null,
      quickReplies: null,
      source: null,
      audioDurationSec: null,
    });
  }

  /**
   * A user who's never worked before has nothing for `experience` — the
   * contract itself says `projects` takes its place in that case. Swaps the
   * `experience` entry in the session's own section list for `projects` at
   * the same position and moves `currentSection` there. No CV/transaction
   * involved: there's no card to confirm for a section that's being skipped.
   */
  async switchExperienceToProjects(session: ConversationSession): Promise<void> {
    const index = session.sections.findIndex((section) => section.id === 'experience');
    if (index === -1) {
      return;
    }
    session.sections[index] = { id: 'projects', label: SECTION_LABELS.projects, status: 'pending' };
    session.currentSection = 'projects';
    await this.conversationRepository.saveSession(session);
  }

  isLastSection(session: ConversationSession, sectionId: SectionId): boolean {
    const index = session.sections.findIndex((section) => section.id === sectionId);
    return index !== -1 && index === session.sections.length - 1;
  }

  /**
   * Confirms the message's card into the CV (applying `edits` if given),
   * marks the section confirmed, and advances currentSection. Section order
   * comes from the session's own `sections` list — not the client's `isLast`
   * flag, which is accepted for contract-shape compliance but not otherwise
   * trusted — so the upload flow (a different, shorter section list) works
   * here unchanged later.
   */
  async confirmSection(
    sessionId: string,
    deviceId: string,
    sectionId: SectionId,
    dto: ConfirmSectionDto,
  ): Promise<ConfirmSectionResponseDto> {
    const session = await this.getActiveOwnedSession(sessionId, deviceId);

    if (session.currentSection !== sectionId) {
      throw new AppError('INVALID_REQUEST', 'السكشن ده مش اللي دورك عليه دلوقتي', { retryable: false });
    }

    const message = await this.conversationRepository.findMessageById(dto.messageId);
    if (!message || message.sessionId !== session.id) {
      throw new AppError('NOT_FOUND', 'الرسالة دي مش موجودة', { retryable: false });
    }
    if (message.type !== 'section_card' || message.section !== sectionId || message.card === null) {
      throw new AppError('INVALID_REQUEST', 'الرسالة دي مالهاش كارت للسكشن ده', { retryable: false });
    }

    const content = this.resolveSectionContent(sectionId, message.card, dto.edits);

    const sectionIndex = session.sections.findIndex((section) => section.id === sectionId);
    const nextSection = session.sections[sectionIndex + 1]?.id ?? null;
    const sessionStatus: SessionStatus = nextSection === null ? 'completed' : 'in_progress';

    const { cvId, nextMessage } = await this.dataSource.transaction(async (manager) => {
      const result = await this.cvService.confirmSection(deviceId, session.cvId, sectionId, content, nextSection === null, manager);

      session.sections[sectionIndex] = { ...session.sections[sectionIndex], status: 'confirmed' };
      session.currentSection = nextSection;
      session.cvId = result.cvId;
      session.status = sessionStatus;
      await this.conversationRepository.saveSession(session, manager);

      // Persisted in the same transaction as the confirm itself, so it comes back with
      // GET /conversations/:id too and is part of the history the model sees next turn — the client
      // doesn't have to guess it from `nextSection`.
      const message = await this.conversationRepository.createMessage(
        {
          id: generateId('msg'),
          sessionId: session.id,
          role: 'ai',
          section: nextSection,
          type: 'text',
          text: nextSection === null ? CV_COMPLETE_MESSAGE : SECTION_OPENING_MESSAGES[nextSection],
          card: null,
          quickReplies: null,
          source: null,
          audioDurationSec: null,
        },
        manager,
      );

      return { ...result, nextMessage: message };
    });

    return {
      section: sectionId,
      status: 'confirmed',
      nextSection,
      sessionStatus,
      cvId: sessionStatus === 'completed' ? cvId : null,
      nextMessage: toMessageResponseDto(nextMessage),
    };
  }

  private resolveSectionContent(
    sectionId: SectionId,
    card: Record<string, unknown> | unknown[],
    edits: Record<string, unknown> | unknown[] | null | undefined,
  ): Record<string, unknown> | unknown[] {
    if (edits === undefined || edits === null) {
      return card;
    }
    const result = CARD_SCHEMA_BY_SECTION[sectionId].safeParse(edits);
    if (!result.success) {
      throw new AppError('INVALID_REQUEST', 'التعديلات اللي بعتها مش بالشكل الصحيح', { retryable: false });
    }
    return result.data as Record<string, unknown> | unknown[];
  }

  private async getOwnedSession(sessionId: string, deviceId: string): Promise<ConversationSession> {
    const session = await this.conversationRepository.findById(sessionId);
    if (!session || session.deviceId !== deviceId) {
      throw new AppError('NOT_FOUND', 'الجلسة دي مش موجودة', { retryable: false });
    }
    return session;
  }

  private async deleteSessionAndItsCv(session: ConversationSession): Promise<void> {
    await this.dataSource.transaction(async (manager) => {
      if (session.cvId) {
        await this.cvService.deleteById(session.cvId, manager);
      }
      await this.conversationRepository.deleteById(session.id, manager);
    });
  }

  private toResponseDto(session: ConversationSession, messages: Message[]): ConversationResponseDto {
    return {
      sessionId: session.id,
      mode: session.mode,
      sections: session.sections,
      currentSection: session.currentSection,
      messages: messages.map(toMessageResponseDto),
      status: session.status,
    };
  }
}
